GET http://localhost:3000/djs

##########

POST http://localhost:3000/djs
Content-Type: application/json

{
  "nome": "Vegas"
}

####

GET http://localhost:3000/djs/2

####

DELETE  http://localhost:3000/djs/2

####

PUT http://localhost:3000/djs/2
Content-Type: application/json

{
  "nome": "Menumas",
  "musicas": [
    {
      "nome": "Inner Voice",
      "genro": "psy trance"
    }
  ]
}

