POST localhost:3000/sistema
Content-Type: application/json

{
  "nome": "NPC",
  "cooperativa": "566"
}

#####

GET localhost:3000/sistema/b8655460-ae75-46d0-b27f-6b89d330f22f

#####

DELETE localhost:3000/sistema/ddc58759-8204-406d-a079-c326f496e4c0

#####

GET localhost:3000/sistema
