POST localhost:3000/features
Content-Type: application/json

{
  "nome": "LISTAR_TITULOS",
  "sistema": "b8655460-ae75-46d0-b27f-6b89d330f22f",
  "habilitado": true
}

###

GET localhost:3000/features/8b6b0f00-aebb-453e-ac67-09f1dfeeb6c1

###

DELETE localhost:3000/features/b243559f-ddf9-4eb7-a740-674ece41cec7

####

GET localhost:3000/features/